CREATE TABLE COL_WRITING_TASK_RECORD (
      record_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '记录ID',
      task1_id BIGINT NOT NULL COMMENT '关联Task1的题目ID',
      task2_id BIGINT NOT NULL COMMENT '关联Task2的题目ID',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
      CONSTRAINT fk_task1 FOREIGN KEY (task1_id) REFERENCES COL_WRITING_TASK(task_id) ON DELETE CASCADE,
      CONSTRAINT fk_task2 FOREIGN KEY (task2_id) REFERENCES COL_WRITING_TASK(task_id) ON DELETE CASCADE
) COMMENT='记录Task1和Task2的题目ID表';
# 写作题目表
CREATE TABLE COL_WRITING_TASK (
          task_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '写作题目ID',
          task_title VARCHAR(500) COMMENT '写作题目标题',
          task_description LONGTEXT COMMENT '写作题目描述',
          task_type VARCHAR(255) COMMENT '写作题目类型ENUM(''TASK1'', ''TASK2'')',
          task_requirements LONGTEXT COMMENT '写作要求',
          word_limit INT COMMENT '字数限制',
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='雅思机考写作题目表';

# 用户写作答题记录主表
CREATE TABLE COL_WRITE_USER_ANSWER_RECORD (
    record_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '唯一答题记录ID',
    user_id INT COMMENT '关联COL_Users.user_id',
    test_id BIGINT COMMENT '关联测试ID（如果适用）',
    task1_id BIGINT COMMENT '关联Task1的题目ID',
    task2_id BIGINT COMMENT '关联Task2的题目ID',
    total_score DECIMAL(5,2) COMMENT '总得分',
    duration_seconds INT COMMENT '答题总耗时（秒）',
    device_type ENUM('WEB','MOBILE','TABLET') COMMENT '作答设备类型',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '答题开始时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间'
) COMMENT='用户写作答题记录表';

# 用户写作答题明细表
CREATE TABLE COL_WRITE_USER_ANSWER_DETAIL (
       detail_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '明细ID',
       user_id INT COMMENT '关联COL_Users.user_id',
       record_id BIGINT NOT NULL COMMENT '关联用户写作答题记录主表ID。COL_WRITE_USER_ANSWER_RECORD.record_id',
       task_type VARCHAR(255) NOT NULL COMMENT '写作题目类型ENUM(''TASK1'', ''TASK2'')',
       answer_content TEXT COMMENT '写作答案内容',
       answer_evaluation TEXT COMMENT '写作答案评价',
       score DECIMAL(5,2) COMMENT '该任务得分',
       duration_seconds INT COMMENT '该任务答题耗时（秒）',
       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间'
) COMMENT='用户写作答题明细表';


-- 外键创建语句（注释掉）
/*
ALTER TABLE COL_WRITE_USER_ANSWER_RECORD
ADD CONSTRAINT fk_write_record_user
FOREIGN KEY (user_id) REFERENCES COL_Users(user_id) ON DELETE CASCADE;

ALTER TABLE COL_WRITE_USER_ANSWER_RECORD
ADD CONSTRAINT fk_write_record_task1
FOREIGN KEY (task1_id) REFERENCES COL_WRITING_TASK(task_id) ON DELETE SET NULL;

ALTER TABLE COL_WRITE_USER_ANSWER_RECORD
ADD CONSTRAINT fk_write_record_task2
FOREIGN KEY (task2_id) REFERENCES COL_WRITING_TASK(task_id) ON DELETE SET NULL;

ALTER TABLE COL_WRITE_USER_ANSWER_DETAIL
ADD CONSTRAINT fk_write_detail_record
FOREIGN KEY (record_id) REFERENCES COL_WRITE_USER_ANSWER_RECORD(record_id) ON DELETE CASCADE;
*/

# 写作评分维度表
CREATE TABLE COL_WRITING_SCORE_DIMENSION (
    dimension_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '评分维度ID',
    task_id BIGINT NOT NULL COMMENT '关联写作题目表COL_WRITING_TASK.task_id',
    dimension_name VARCHAR(255)   COMMENT '评分维度名称',
    dimension_description TEXT   COMMENT '评分维度描述',
    max_score INT DEFAULT 25 COMMENT '该维度满分',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='雅思机考写作评分维度表';

-- 外键创建语句（注释掉）
/*
ALTER TABLE COL_WRITING_SCORE_DIMENSION
ADD CONSTRAINT fk_writing_score_dimension_task
FOREIGN KEY (task_id) REFERENCES COL_WRITING_TASK(task_id) ON DELETE CASCADE;
*/

# 写作答案评分明细表
CREATE TABLE COL_WRITING_ANSWER_SCORE (
    score_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '评分明细ID',
    answer_id BIGINT NOT NULL COMMENT '关联COL_WRITE_USER_ANSWER_DETAIL.detail_id',
    dimension_id BIGINT NOT NULL COMMENT '关联写作评分维度表COL_WRITING_SCORE_DIMENSION.dimension_id',
    max_score INT DEFAULT 25 COMMENT '该维度满分',
    score DECIMAL(5,2) COMMENT '得分',
    comments TEXT COMMENT '评分评语',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '评分时间'
) COMMENT='雅思机考写作答案评分明细表';

-- 外键创建语句（注释掉）
/*
ALTER TABLE COL_WRITING_ANSWER_SCORE
ADD CONSTRAINT fk_writing_answer_score_answer
FOREIGN KEY (answer_id) REFERENCES COL_USER_WRITING_ANSWER(answer_id) ON DELETE CASCADE;

ALTER TABLE COL_WRITING_ANSWER_SCORE
ADD CONSTRAINT fk_writing_answer_score_dimension
FOREIGN KEY (dimension_id) REFERENCES COL_WRITING_SCORE_DIMENSION(dimension_id) ON DELETE CASCADE;
*/

ALTER TABLE COL_WRITING_TASK MODIFY task_title VARCHAR(500);
ALTER TABLE COL_WRITING_TASK MODIFY task_description TEXT;