-- 创建听力材料表（COL_LISTENING）
CREATE TABLE COL_LISTENING (
     COL_ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '听力材料ID',
     COL_TITLE VARCHAR(255) COMMENT '听力材料标题',
     COL_CONTENT TEXT COMMENT '听力材料内容',
     COL_AUDIO_URL VARCHAR(255) COMMENT '听力材料音频URL',
     COL_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
     COL_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='听力材料表';

-- 创建听力题目表（COL_LISTENING_QUESTION）
CREATE TABLE COL_LISTENING_QUESTION (
    COL_ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '题目ID',
    COL_LISTENING_ID BIGINT COMMENT '关联的听力材料ID', -- 关联COL_LISTENING(COL_ID)
    COL_TYPE ENUM('SINGLE_CHOICE', 'FILL_IN_THE_BLANK', 'MATCHING') COMMENT '题目类型',
    COL_CONTENT TEXT COMMENT '题目内容',
    COL_PLACEHOLDER_FORMAT VARCHAR(255) COMMENT '填空题占位符格式（如 "{{1}} and {{2}}"）',
    COL_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    COL_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COL_PART ENUM('Part1', 'Part2', 'Part3', 'Part4') COMMENT '题目所属部分',
    COL_IMAGE_URL  VARCHAR(255) NULL COMMENT '题目图片URL'
) COMMENT='听力题目表';

-- 创建听力答案表（COL_LISTENING_ANSWER）
CREATE TABLE COL_LISTENING_ANSWER (
    COL_ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '答案ID',
    COL_QUESTION_ID BIGINT COMMENT '关联的题目ID', -- 关联COL_LISTENING_QUESTION(COL_ID)
    COL_CONTENT TEXT COMMENT '答案内容',
    COL_IS_CORRECT BOOLEAN DEFAULT FALSE COMMENT '是否为正确答案（用于选择题）',
    COL_BLANK_NUMBER INT COMMENT '填空题空的序号（如 1, 2）',
    COL_MATCHING_KEY VARCHAR(50) COMMENT '配对题的匹配键（如 "A", "B"）',
    COL_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    COL_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COL_PART ENUM('Part1', 'Part2', 'Part3', 'Part4') COMMENT '题目所属部分'
) COMMENT='听力答案表';

-- 创建用户听力答题记录主表（COL_LISTEN_USER_ANSWER_RECORD）
CREATE TABLE COL_LISTEN_USER_ANSWER_RECORD (
    RECORD_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '唯一答题记录ID',
    USER_ID INT COMMENT '关联COL_Users.user_id', -- 关联COL_Users(user_id)
    LISTENING_ID BIGINT COMMENT '关联听力材料ID', -- 关联COL_LISTENING(COL_ID)
    SCORE DECIMAL(5,2) COMMENT '本次答题得分',
    ANSWER_EVALUATION TEXT COMMENT '答题评价',
    DURATION_SECONDS INT COMMENT '答题耗时（秒）',
    DEVICE_TYPE ENUM('WEB','MOBILE','TABLET') COMMENT '答题设备类型',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '答题开始时间',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    COL_PART ENUM('Part1', 'Part2', 'Part3', 'Part4') COMMENT '题目所属部分'
) COMMENT='用户听力答题主记录表（1条记录对应多个答案明细）';

-- 创建用户听力答题明细表（COL_LISTEN_USER_ANSWER_DETAIL）
CREATE TABLE COL_LISTEN_USER_ANSWER_DETAIL (
    DETAIL_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '答案明细ID',
    RECORD_ID BIGINT COMMENT '关联COL_LISTEN_USER_ANSWER_RECORD.RECORD_ID', -- 关联用户听力答题记录主表ID
    USER_ID INT COMMENT '关联COL_Users.user_id', -- 关联COL_Users(user_id)
    QUESTION_ID BIGINT COMMENT '关联COL_LISTENING_QUESTION.COL_ID', -- 关联COL_LISTENING_QUESTION(COL_ID)
    ANSWER_TYPE ENUM('SINGLE_CHOICE', 'FILL_IN_THE_BLANK', 'MATCHING') COMMENT '对应题目类型',
    SUBMITTED_ANSWER TEXT COMMENT '用户提交答案（JSON格式）',
    IS_CORRECT BOOLEAN COMMENT '是否正确（自动批改时填充）',
    BLANK_INDEX INT COMMENT '填空题空序号（当ANSWER_TYPE=FILL_IN_THE_BLANK时有效）',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间',
    COL_PART ENUM('Part1', 'Part2', 'Part3', 'Part4') COMMENT '题目所属部分'
) COMMENT='用户听力答案明细表（通过RECORD_ID实现批量关联）';

# -- 修改听力题目表（COL_LISTENING_QUESTION），增加字段 COL_PART
# ALTER TABLE COL_LISTENING_QUESTION
#     ADD COLUMN COL_PART ENUM('Part1', 'Part2', 'Part3', 'Part4') COMMENT '题目所属部分' AFTER COL_UPDATED_AT;