server:
  port: 9091

spring:
  application:
    name: mock-ielts-users
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        namespace: 1695f1a3-225f-4479-9dc1-1f71f7c845a7
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        client-ip: 127.0.0.1
  logging:
    level:
      root: WARN  # 只显示 WARN 及以上级别的日志
      com.apps: INFO  # 对 com.apps 包的日志级别设置为 INFO
feign:
  sentinel:
    enabled: true


